### ISSUE TITLE
Relocation error in Lambda invocation.  Due to packager not following nested symlink?

### ISSUE THREAD

**Issue by webbnh** [awslabs/aws-lambda-cpp#19]
When I test my Lambda function via the "Test" button on the AWS Lambda "console" web page, I get the following in the log:
```
START RequestId: 87a9968e-0f96-11e9-9807-e18356b5372b Version: $LATEST
/bin/bash: relocation error: lib/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
END RequestId: 87a9968e-0f96-11e9-9807-e18356b5372b
```

If I unpack my `.zip` file locally, the tail of the output looks like this:
```
  inflating: [...]
finishing deferred symbolic links:
  lib/libm.so.6          -> libm-2.23.so
  [...]
  lib/libc.so.6          -> libc-2.23.so
  [...]
  lib/ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-2.23.so
  [...]
  lib/libnss_dns.so.2    -> libnss_dns-2.23.so
```

I note that of all the symlinks it creates, only the one for `ld-linux-x86-64.so.2` contains a full, absolute path.

I'm gonna guess that it's because, on my system, `/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2` is itself a symlink (to `/lib/x86_64-linux-gnu/ld-2.23.so`), and so the packager is getting the symlink file where it should be _following_ the symlink to the actual file...with the result that my Lambda is actually referencing the underlying system's library instead of the one that it's supposed to have brought with it in the bundle.

(I'm building on `Linux ip-172-31-27-38 4.4.0-1070-aws #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`.)

**Comment by marcomagdy** [comment]
Are you using v0.1.0? or HEAD?

**Comment by marcomagdy** [comment]
Yep, I'm able to reproduce it. I'll have a path ready in a few. Thanks for reporting the problem

**Comment by webbnh** [comment]
Thanks for the awesome responsiveness!

However, (I think) I've manually repaired the link problem in the `.zip` file, and I'm still getting the same result from the test.  :-(

My unpacked files look like this:
```
$ ls -l lib/ld-*
-rwxr-xr-x 1 webb webb 162632 Jan  3 21:40 lib/ld-2.23.so
lrwxrwxrwx 1 webb webb     10 Jan  3 21:41 lib/ld-linux-x86-64.so.2 -> ld-2.23.so
```

I guess I'll switch to v0.1.0 (which I what I'd meant to pull down...), and see if that brings more joy.

**Comment by marcomagdy** [comment]
your bootstrap file is probably busted though. That's why when you fixed the link it didn't help.

**Comment by webbnh** [comment]
Using `v0.1.0`, I get no symlinks:
```
$ ls -l lib/ld-*
-rwxr-xr-x 1 webb webb 162632 Jan  3 21:52 lib/ld-2.23.so
-rwxr-xr-x 1 webb webb 162632 Jan  3 21:53 lib/ld-linux-x86-64.so.2
```
which I presume is no surprise.  However, I'm still getting the error on test:
```
/bin/bash: relocation error: lib/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

(I'm reasonably sure that I'm producing a fresh bundle, actually copying it to S3, and actually updating the Lambda with it....)

There's no reason to think that this stuff _shouldn't_ work on Ubuntu 16.04.5 LTS...right?

**Comment by marcomagdy** [comment]
>There's no reason to think that this stuff shouldn't work on Ubuntu 16.04.5 LTS...right?

right. It should work on most linux distros. Especially the mainstream ones.

**Comment by webbnh** [comment]
OK, so the weird thing that I'm doing (there had to be one...right?), is I have a bunch of shared libraries which are dynamically loaded.  So, I add them to the bundle:
```
$ zip mylambda.zip ExtObjs/libmyextras.kind.*
```
And then in my Lambda definition, I supply a definition for the `LD_LIBRARY_PATH` environment variable:  "`lib:ExtObjs`".  Could that be causing the problem?  (Or, have I not gotten far enough to hit those sorts of problems, yet?)

**Comment by marcomagdy** [comment]
This should fix the original symlink issue https://github.com/awslabs/aws-lambda-cpp/pull/20

**Comment by webbnh** [comment]
> Try using the full path in LD_LIBRARY_PATH. `/var/task/lib:/var/task/ExtObjs`

That changed the behavior, but not the result.  (I still see the previous error, but now I get it without the `START`/`END`/`REPORT` messages.)

I tried just removing the definition of `LD_LIBRARY_PATH`.  This seemed to "work", in that I think my code ran up to the point where it couldn't dynamically load my libraries.

I tweaked my code to print out the value of `LD_LIBRARY_PATH`, and, by default, it appears to be
```
/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
```
So, I used that, with my extra directory tacked on to the end, and it seems to "work" as far as I can tell without real data.  (So, apparently, I needed at least one more directory than just `/var/task/lib`.)

Anyway, I think I'm in business, now.  Thanks so much for your help!!
